// ARRAY CHAMADO IDADES COM VALORES DIFERENTES. VERIFICAR QUAIS IDADES SÃO MAIORES QUE 18 E EXIBIR: "É MAIOR DE IDADE" OU "É MENOR DE IDADE"

let idades = [9, 12, 15, 18, 21, 32]

for (let i = 0; i < 18; i++) {
  console.log()
}